
services:
  boavizta:
    image: ghcr.io/boavizta/boaviztapi:latest
    ports:
      - 5000:5000

  backend:
    build:
      context: .
    command: /app/bin/server
    depends_on:
      - boavizta
    ports:
      - 8082:8082

  gateway:
    build:
      context: .
    command: /app/bin/gateway
    depends_on:
      - boavizta
      - backend
    ports:
      - 8083:8083

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - .:/app/
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - .:/app
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
