
services:
  boavizta:
    image: ghcr.io/boavizta/boaviztapi:latest
    ports:
      - 5000:5000

  backend:
    build: .
    command: /app/bin/server
    depends_on:
      - boavizta
    ports:
      - 8082:8082

  gateway:
    build: .
    command: /app/bin/gateway
    depends_on:
      - boavizta
      - backend
    ports:
      - 8083:8083

  nginx:
    image: nginx:latest
    depends_on:
      - gateway
    ports:
      - 8081:80
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
