version: '3'

tasks:
  proto:
    cmds:
      - |
        protoc \
          --go_out=. \
          --go_opt=paths=source_relative \
          --go-grpc_out=. \
          --go-grpc_opt=paths=source_relative \
          api/grpc/v1/usage.proto
      - |
        protoc \
          -I . \
          --grpc-gateway_out . \
          --grpc-gateway_opt logtostderr=true \
          --grpc-gateway_opt paths=source_relative \
          --grpc-gateway_opt generate_unbound_methods=true \
          api/grpc/v1/usage.proto

  server:
    cmds:
      - go run cmd/server/main.go

  gateway:
    cmds:
      - go run cmd/gateway/main.go

  boavizta:
    cmds:
      - docker compose up -d boavizta

  test:
    cmds:
      - go test -v $(go list ./... | grep -v /e2e)

  test-e2e:
    cmds:
      - go clean -testcache
      - go test -v $(go list ./e2e/...)

  vm-install:
    cmds:
      - cd ansible && ansible-playbook -i inventory/all.yml install.yml

  vm-deploy:
    cmds:
      - cd ansible && ansible-playbook -i inventory/all.yml deploy.yml

  dev-nginx:
    cmds:
      - NGINX_CONF_DIR=./nginx/conf-dev/ docker compose up nginx -d

  dev-up:
    cmds:
      - NGINX_CONF_DIR=./nginx/conf-dev/ docker compose up -d
