---

- name: Deploy
  hosts: vms
  tasks:
    - name: Copy to VM
      ansible.posix.synchronize:
        src: "{{ playbook_dir}}/../"
        dest: /root/app

    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: /root/app
        state: absent

    - name: Prune Docker cache
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true

    - name: Build images
      community.docker.docker_compose_v2:
        project_src: /root/app
        build: always
        state: present

    - name: Start up services
      community.docker.docker_compose_v2:
        project_src: /root/app
        state: present

    - name: Prune Docker cache
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
